#pragma once

#include <stdint.h>

#define SERVER_PROTOCOL_VERSION 754

#define SERVER_MAX_PLAYERS 4
#define SERVER_TCP_PORT 25565

#define SERVER_NET_TASK_STACK (10 * 1024)
#define SERVER_NET_TASK_PRIORITY 19
#define SERVER_TICK_MS 25

#define SERVER_RX_STREAM_BUFFER 4096
#define SERVER_MAX_INBOUND_PACKET_SIZE 1536
#define SERVER_MAX_OUTBOUND_PACKET_SIZE (32 * 1024)
#define SERVER_MAX_CHUNK_DATA_SIZE (24 * 1024)
#define SERVER_MAX_PACKET_SIZE SERVER_MAX_INBOUND_PACKET_SIZE
#define SERVER_SOCKET_SEND_STALL_RETRIES 100

#define SERVER_MAX_CHAT_MESSAGE_LENGTH 128

#define SERVER_CHUNK_SEND_RADIUS 0
#define SERVER_CHUNK_SENDS_PER_TICK 1
#define SERVER_CHUNK_TRACKED_MAX 16
#define SERVER_VIEW_DISTANCE_CHUNKS 2

#define WORLD_SEED_DEFAULT 1337u
#define WORLD_MIN_Y 0
#define WORLD_MAX_Y 128
#define WORLD_SEA_LEVEL 62
#define WORLD_ANCHOR_STEP 32

#define WORLD_MAX_BLOCK_DELTAS 2048
