#pragma once

#include <stdint.h>

#define SERVER_PROTOCOL_VERSION 754

#define SERVER_MAX_PLAYERS 4
#define SERVER_TCP_PORT 25565

#define SERVER_NET_TASK_STACK (8 * 1024)
#define SERVER_NET_TASK_PRIORITY 19
#define SERVER_TICK_MS 50

#define SERVER_RX_STREAM_BUFFER 4096
#define SERVER_MAX_PACKET_SIZE 1536

#define WORLD_SEED_DEFAULT 1337u
#define WORLD_MIN_Y 0
#define WORLD_MAX_Y 128
#define WORLD_SEA_LEVEL 62
#define WORLD_ANCHOR_STEP 32

#define WORLD_MAX_BLOCK_DELTAS 6000
